application: your-project-id
version: alpha6
runtime: php55
api_version: 1
threadsafe: yes


handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /inc
  static_dir: inc
  
- url: /
  script: upload.php
